### ISSUE TITLE
chefkoch.de website not supported and aweful in the browser

### ISSUE THREAD

**Issue by samuelgfeller** [jpbulman/OnlyTheRecipe#23]
I mean, have a look for yourself:
![Screenshot_20220227-202829_Samsung Internet](https://user-images.githubusercontent.com/31797204/155896852-a89bfe83-6443-497e-8bb3-2ae671e31a32.jpg)
This website is not fun to use. One ad is way too wide and messes up the responsivness and they don't fix it. 
I'd love being able to see a clean version of my favourite cookie recipe!

Cheers to you for doing the work!

**Comment by jpbulman** [comment]
Whoops, I thought your pr comment would auto-close this. 

Well I don't have that specific link to test, @MRuy seems to have fixed it! Feel free to reopen if this is still not supported
